## Dibetes Prediction

In [84]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [85]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
df = pd.DataFrame(diabetes['data'])

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       442 non-null    float64
 1   1       442 non-null    float64
 2   2       442 non-null    float64
 3   3       442 non-null    float64
 4   4       442 non-null    float64
 5   5       442 non-null    float64
 6   6       442 non-null    float64
 7   7       442 non-null    float64
 8   8       442 non-null    float64
 9   9       442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [87]:
df

            0         1         2  ...         7         8         9
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [88]:
diabetes['feature_names']

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [89]:
x = pd.DataFrame(diabetes['data'])
y = diabetes['target']

In [90]:
# train test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , train_size=0.80 , random_state= 10)

In [91]:
x_train

            0         1         2  ...         7         8         9
252  0.005383 -0.044642  0.059541  ...  0.050914 -0.004222 -0.030072
416 -0.027310 -0.044642  0.080019  ...  0.003312 -0.029526  0.036201
418  0.009016 -0.044642 -0.024529  ... -0.002592 -0.021395  0.007207
163  0.016281  0.050680  0.072474  ... -0.002592 -0.023647  0.061054
253  0.081666 -0.044642  0.033673  ...  0.034309  0.034866  0.069338
..        ...       ...       ...  ...       ...       ...       ...
369 -0.009147 -0.044642  0.037984  ...  0.015858 -0.005142  0.027917
320 -0.023677 -0.044642  0.030440  ...  0.071210  0.033043  0.003064
15  -0.052738  0.050680 -0.018062  ...  0.108111  0.036060 -0.042499
125 -0.005515  0.050680 -0.008362  ... -0.002592  0.080590  0.007207
265 -0.034575  0.050680 -0.025607  ... -0.015508  0.014821  0.040343

[353 rows x 10 columns]

In [92]:
from sklearn.tree import DecisionTreeRegressor
tree_regressor = DecisionTreeRegressor()
tree_regressor.fit(x_train , y_train)
y_pred = tree_regressor.predict(x_test)

In [93]:
# visulize the dicision tree
# from sklearn import tree
# plt.figure(figsize=(15,10))
# tree.plot_tree(tree_regressor , filled=True)

In [94]:
# check accuracy
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
# print(classification_report(y_test , y_pred))
print(accuracy_score(y_test , y_pred))
# print(confusion_matrix(y_test , y_pred))

0.011235955056179775

c:\Users\YASH JAIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\YASH JAIN\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_pred = type_of_target(y_pred, input_name="y_pred")

In [95]:
# hyperpara meter tunning
param = {
    
    'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'splitter':['best', 'random'],
    'max_depth':[1,2,3,4,5],
    'max_features':['sqrt', 'log2']
}

In [96]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(tree_regressor , param_grid=param , cv=5 , scoring='neg_mean_squared_error' )
grid.fit(x_train , y_train)
y_pred = grid.predict(x_test)

In [97]:
grid.best_params_

{'criterion': 'squared_error',
 'max_depth': 3,
 'max_features': 'log2',
 'splitter': 'best'}

In [98]:
# check accuracy
from sklearn.metrics import mean_absolute_error , mean_squared_error
# print(classification_report(y_test , y_pred))
print(mean_squared_error(y_test ,y_pred))
print(mean_absolute_error(y_test , y_pred))

4917.051911305546
53.65626081050806